name: Run Python Tests

on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'README.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest - without end to end
        run: python -m pytest tests -m 'not e2e' 

      - name: Run coverage
        run: |
          pip install pytest-cov
          python -m pytest tests -m 'not e2e' --cov=blog